[package]
name = "factory_anchor_long"
version = "0.1.1"
authors = ["Frank Hillard <frank.hillard@gmail.com>"]
description = "Factory of anchoring contracts."
readme = "README.md"
license = "MIT"
keywords = ["factory", "anchor", "starknet"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.6.3"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.1" }

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
casm = true
# sierra = true

# build-external-contracts = ["openzeppelin::account::account::Account"]

[scripts]
test = "snforge test factory_anchor_long"
